### PR TITLE
vec_avx.h

### PR DESCRIPTION
**Pull request by xueyingxue001**
Add openmp

### CODE REVIEW

**Comment by npuichigo** [comment]
What about the speed after adding openmp?

**Comment by rafael2k** [comment]
Also, please add openmp support for the pure-C implementation, where it makes even more sense, IMHO.

**Comment by jmvalin** [comment]
OpenMP isn't useful here because we're already running in real time easily on just one core, so there's no need to parallelize. That would just increase the overall cost (due to communications and all), with no real benefit.

**Comment by sheepHavingPurpleLeaf** [comment]
> Add openmp

is there any improvement on RTF? how much

**Comment by sheepHavingPurpleLeaf** [comment]
> Add openmp

is there any improvement on RTF? how much

**Pull request closed without merging**
